---
site_name: "biocore-data-model-linkml-template"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://turbomam.github.io/biocore-data-model-linkml-template
repo_url: https://github.com/turbomam/biocore-data-model-linkml-template

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
